version: '3'
services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/users
    depends_on:
      - mongo

  post-service:
    build: ./post-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/posts
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
