version: '3.1'
services:
  user-service:
    build: ./user-service
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app/user-service/
    environment:
      - MONGO_URL=mongodb://mongo_db:27017/users
    depends_on:
      - mongo_db

  post-service:
    build: ./post-service
    ports:
      - "3001:3001"
    volumes:
      - .:/home/app/post-service/
    environment:
      - MONGO_URL=mongodb://mongo_db:27017/posts
    depends_on:
      - mongo_db

  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - "2717:27017"
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db: {}
