apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-service
  template:
    metadata:
      labels:
        app: post-service
    spec:
      containers:
      - name: post-service
        image: mohdaqib1/post-service:latest
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URL
          value: mongodb://mongo-db-service:27017/posts
        volumeMounts:
        - name: post-service-volume
          mountPath: /home/app/post-service
      volumes:
      - name: post-service-volume
        persistentVolumeClaim:
          claimName: post-service-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: post-service
spec:
  type: NodePort
  selector:
    app: post-service
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001  # NodePort can be between 30000-32767
