apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: mohdaqib1/user-service:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: mongodb://mongo-db-service:27017/users
        volumeMounts:
        - name: user-service-volume
          mountPath: /home/app/user-service
      volumes:
      - name: user-service-volume
        persistentVolumeClaim:
          claimName: user-service-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000  # NodePort can be between 30000-32767
